
name: 'loadsmart_dbt'
version: '1.0.0'

profile: 'loadsmart_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  loadsmart_dbt:
    +materialized: view

    staging:
      # +schema: stg
      +materialized: view

    marts:
      # +schema: mart
      +materialized: table
