loadsmart_dbt:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: loadsmart_user
      password: loadsmart_password
      dbname: loadsmart_challenge
      schema: analytics
      threads: 4
  target: dev